// Generated by scripts/sync-demos.ts — do not edit.
//
// Eight characters of each file's own hash, so a changed demo or poster is a
// new URL. Without this the seven-day cache served a corrected image to nobody.
export const ASSET_HASHES: Readonly<Record<string, { demo: string; poster: string }>> =
  Object.freeze({
    'string-le': { demo: 'b4b993f5', poster: 'eeffcb71' },
    'numbers-le': { demo: '428c552a', poster: '822fe722' },
    'paths-le': { demo: 'cfc910eb', poster: '760978d0' },
    'colors-le': { demo: '9999de44', poster: 'a00c94e7' },
    'urls-le': { demo: '5bfb0089', poster: 'cf6ce05e' },
    'dates-le': { demo: 'b6b05b59', poster: '8befaecb' },
    'regex-le': { demo: 'b9bdbd59', poster: '8ff44a7b' },
    'scrape-le': { demo: '9fe6c779', poster: 'ee158f95' },
    'secrets-le': { demo: '78688215', poster: 'd0d08739' },
    'envsync-le': { demo: '32b7bcfa', poster: 'e07a144b' },
  })
