// Generated by scripts/sync-registry.ts — do not edit.
//
// Read from each extension repo: the manifest version and command count, the
// translated locale bundles, the MCP package name, and the Zed extension id.
// `bun run sync:registry --check` fails when this drifts from the repos.
import type { ToolFacts } from '../scripts/sync-registry'

export const TOOL_FACTS: Readonly<Record<string, ToolFacts>> = Object.freeze({
  'string-le': { version: '2.2.3', commands: 6, locales: 12, mcpPackage: 'string-le-mcp', zedId: 'string-le' },
  'numbers-le': { version: '2.2.3', commands: 6, locales: 12, mcpPackage: 'numbers-le-mcp', zedId: 'numbers-le' },
  'paths-le': { version: '2.2.3', commands: 5, locales: 12, mcpPackage: 'paths-le-mcp', zedId: 'paths-le' },
  'colors-le': { version: '2.2.3', commands: 9, locales: 12, mcpPackage: 'colors-le-mcp', zedId: 'colors-le' },
  'urls-le': { version: '2.2.3', commands: 5, locales: 12, mcpPackage: 'urls-le-mcp', zedId: 'urls-le' },
  'dates-le': { version: '2.2.3', commands: 9, locales: 12, mcpPackage: 'dates-le-mcp', zedId: 'dates-le' },
  'regex-le': { version: '2.2.3', commands: 5, locales: 12, mcpPackage: 'regex-le-mcp', zedId: 'regex-le' },
  'scrape-le': { version: '2.2.3', commands: 5, locales: 12, mcpPackage: 'scrape-le-mcp', zedId: 'scrape-le' },
  'secrets-le': { version: '2.2.3', commands: 4, locales: 12, mcpPackage: 'secrets-le-mcp', zedId: 'secrets-le' },
  'envsync-le': { version: '2.2.3', commands: 9, locales: 12, mcpPackage: 'envsync-le-mcp', zedId: 'envsync-le' },
})
