#!/usr/bin/env bun
/**
 * Rebuild `public/demos/` from each tool repo's canonical demo.
 *
 * `src/assets/images/demo.gif` is the demo each tool's README embeds, so it is
 * the one users see on the Marketplace listing and on GitHub. This site should
 * show the same recording, and until now the copies were made by hand — which
 * is how Colors-LE ended up shipping the Dates-LE demo, and how every copy here
 * drifted a release behind the source.
 *
 * The recordings are wider than the card, so each is scaled to a fixed width
 * with a per-clip palette. A GIF re-encoded against the global 256-colour
 * palette bands badly on editor screenshots, which are mostly flat syntax
 * colours over a dark background — `palettegen`/`paletteuse` is what keeps
 * them legible.
 *
 * Requires ffmpeg. Run: bun run sync:demos
 */
import { createHash } from 'node:crypto'
import { existsSync, readdirSync, readFileSync, statSync, unlinkSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { TOOLS } from '../lib/tools'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const DEMOS = resolve(ROOT, 'public/demos')
const POSTERS = resolve(ROOT, 'public/posters')
/** The extension repos are checked out beside this one. */
const FLEET = resolve(ROOT, '..')
const MAP = resolve(ROOT, 'lib/asset-hashes.generated.ts')

/** The card renders at 800px; anything wider is bytes nobody sees. */
const WIDTH = 800

export function sourceFor(toolId: string): string {
  return resolve(FLEET, toolId, 'src/assets/images/demo.gif')
}

/**
 * Eight characters of the file's own hash, spliced into its name.
 *
 * The demos and posters are served with a seven-day cache at a stable URL, so
 * replacing one was invisible to every returning visitor until it expired —
 * the Colors-LE screenshot was corrected and people kept seeing the old one.
 * Naming the file after its contents means a changed file is a new URL, and a
 * long cache becomes correct rather than a liability.
 */
export function fingerprint(bytes: Uint8Array): string {
  return createHash('sha1').update(bytes).digest('hex').slice(0, 8)
}

export function destinationFor(toolId: string): string {
  return resolve(DEMOS, `${toolId}.gif`)
}

/**
 * The still shown before the demo plays, and under reduced motion.
 *
 * These were generated once by hand and never again. Two of them were the same
 * file — the Colors-LE card showed the Dates-LE screenshot on every visit,
 * which is the duplicate-demo bug a directory over, and the demo check never
 * looked here. Deriving the poster from the demo means it cannot disagree with
 * the clip it stands in for.
 */
export function posterFor(toolId: string): string {
  return resolve(POSTERS, `${toolId}.jpg`)
}

/** First frame of the clip, at the width the card renders. */
export function posterArgsFor(source: string, destination: string): readonly string[] {
  return [
    '-y',
    '-loglevel',
    'error',
    '-i',
    source,
    '-frames:v',
    '1',
    '-vf',
    `scale=${WIDTH}:-1:flags=lanczos`,
    '-q:v',
    '4',
    destination,
  ]
}

/**
 * The ffmpeg filter chain, as one string. Kept here rather than inline so the
 * encode is one decision in one place — a demo re-encoded with different
 * settings than its neighbours is visible on the grid.
 */
export const FILTER =
  `scale=${WIDTH}:-1:flags=lanczos,split[s0][s1];` +
  '[s0]palettegen=stats_mode=diff[p];[s1][p]paletteuse=dither=bayer:bayer_scale=3'

export function argsFor(source: string, destination: string): readonly string[] {
  return ['-y', '-loglevel', 'error', '-i', source, '-vf', FILTER, destination]
}

/**
 * The committed map the site reads to build each asset URL.
 *
 * Emitted at the indentation biome formats to, so a sync leaves a clean tree.
 * It used to emit its own shape, which meant every `sync:demos` failed `lint`
 * until someone ran `format` — a gate that fails on correct output teaches
 * people to ignore it. Unlike `tool-facts.generated.ts` there is no byte
 * comparison against the repos here, so formatting this file is safe; the test
 * that pins it to this renderer is what keeps the two agreeing.
 */
export function renderHashes(
  hashes: ReadonlyMap<string, { demo: string; poster: string }>,
): string {
  const entries = [...hashes]
    .map(([id, hash]) => `    '${id}': { demo: '${hash.demo}', poster: '${hash.poster}' },`)
    .join('\n')
  return `// Generated by scripts/sync-demos.ts — do not edit.
//
// Eight characters of each file's own hash, so a changed demo or poster is a
// new URL. Without this the seven-day cache served a corrected image to nobody.
export const ASSET_HASHES: Readonly<Record<string, { demo: string; poster: string }>> =
  Object.freeze({
${entries}
  })
`
}

export async function main(): Promise<number> {
  // A repo with no `src/assets/images/` at all has no extension in it yet —
  // there is no editor screen to record, so there is nothing to copy and
  // nothing wrong. A repo that has the directory and not the demo is the
  // failure this used to catch, and still does.
  const recorded = TOOLS.filter(tool => existsSync(resolve(FLEET, tool.id, 'src/assets')))
  const missing = recorded.filter(tool => !existsSync(sourceFor(tool.id)))
  if (missing.length > 0) {
    process.stderr.write(
      `\nsync-demos: no source demo for ${missing.map(t => t.id).join(', ')}.\n` +
        `Expected each tool repo checked out beside this one, at ${FLEET}.\n\n`,
    )
    return 2
  }

  let total = 0
  const hashes = new Map<string, { demo: string; poster: string }>()
  for (const tool of recorded) {
    const destination = destinationFor(tool.id)
    const result = Bun.spawnSync(['ffmpeg', ...argsFor(sourceFor(tool.id), destination)])

    if (result.exitCode !== 0) {
      process.stderr.write(
        `\nsync-demos: ffmpeg failed for ${tool.id}.\n${result.stderr.toString()}\n`,
      )
      return 1
    }

    const poster = posterFor(tool.id)
    const posterResult = Bun.spawnSync(['ffmpeg', ...posterArgsFor(sourceFor(tool.id), poster)])
    if (posterResult.exitCode !== 0) {
      process.stderr.write(
        `\nsync-demos: ffmpeg failed on the poster for ${tool.id}.\n${posterResult.stderr.toString()}\n`,
      )
      return 1
    }

    const demoHash = fingerprint(readFileSync(destination))
    const posterHash = fingerprint(readFileSync(poster))
    hashes.set(tool.id, { demo: demoHash, poster: posterHash })

    // The served name carries the hash; the unsuffixed file is the working
    // copy the next sync overwrites.
    const servedDemo = resolve(DEMOS, `${tool.id}.${demoHash}.gif`)
    const servedPoster = resolve(POSTERS, `${tool.id}.${posterHash}.jpg`)
    writeFileSync(servedDemo, readFileSync(destination))
    writeFileSync(servedPoster, readFileSync(poster))

    // The unsuffixed encode was a staging file; only the fingerprinted copy
    // ships, so it goes rather than doubling the directory.
    unlinkSync(destination)
    unlinkSync(poster)

    const bytes = statSync(servedDemo).size + statSync(servedPoster).size
    total += bytes
    process.stdout.write(
      `  ${tool.id.padEnd(12)} ${(bytes / 1024).toFixed(0).padStart(5)} KB  ${demoHash}\n`,
    )
  }

  // Anything fingerprinted that this run did not produce is a previous
  // version. Left behind it is dead weight the payload budget still counts.
  const live = new Set<string>()
  for (const [id, hash] of hashes) {
    live.add(`${id}.${hash.demo}.gif`)
    live.add(`${id}.${hash.poster}.jpg`)
  }
  let removed = 0
  for (const [directory, extension] of [
    [DEMOS, '.gif'],
    [POSTERS, '.jpg'],
  ] as const) {
    for (const file of readdirSync(directory)) {
      if (!file.endsWith(extension)) continue
      if (!/\.[0-9a-f]{8}\./.test(file)) continue
      if (live.has(file)) continue
      unlinkSync(resolve(directory, file))
      removed += 1
    }
  }

  writeFileSync(MAP, renderHashes(hashes))
  const skipped = TOOLS.length - recorded.length
  process.stdout.write(
    `\nSynced ${recorded.length} demos and posters, ${(total / 1024 / 1024).toFixed(1)} MB` +
      `${removed > 0 ? `, removed ${removed} superseded file(s)` : ''}` +
      `${skipped > 0 ? `. ${skipped} tool(s) have no extension to record yet` : ''}.\n`,
  )
  return 0
}

/* v8 ignore start -- process entry point; unreachable when imported by a test */
if (import.meta.main) {
  try {
    process.exit(await main())
  } catch (cause) {
    const detail = cause instanceof Error ? (cause.stack ?? cause.message) : String(cause)
    process.stderr.write(`\nsync-demos: unexpected failure — this is a bug.\n${detail}\n\n`)
    process.exit(2)
  }
}
/* v8 ignore stop */
