#!/usr/bin/env bun
/**
 * Derive the per-tool facts from the extension repos, into a generated file.
 *
 * Version, command count, locale count, MCP package name and Zed id are all
 * things the repos already know. Typed by hand here they go stale silently —
 * the site claimed Regex-LE and Secrets-LE were English-only long after both
 * shipped twelve translations, because a sentence in a component was the only
 * place that fact lived.
 *
 * The output is committed, because a Vercel build has no sibling checkouts.
 * `--check` regenerates in memory and fails when the committed file no longer
 * matches the repos, which is what turns a generated file into a gate.
 *
 *   bun run sync:registry          rewrite the generated file
 *   bun run sync:registry --check  fail if it is out of date
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { TOOLS } from '../lib/tools'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
/** The extension repos are checked out beside this one. */
const FLEET = resolve(ROOT, '..')
const OUTPUT = resolve(ROOT, 'lib/tool-facts.generated.ts')

/** One command as the palette shows it. */
export type ToolCommand = Readonly<{ id: string; title: string }>

/** The Rust CLI a tool ships, where it ships one. */
export type CrateFacts = Readonly<{ name: string; version: string }>

export type ToolFacts = Readonly<{
  version: string
  commands: readonly ToolCommand[]
  /** Translated locales, excluding the English base bundle. */
  locales: number
  mcpPackage: string
  zedId: string
  /** Absent for the nine tools that ship no crate. */
  crate?: CrateFacts
}>

function json(path: string): Record<string, unknown> {
  return JSON.parse(readFileSync(path, 'utf8'))
}

export function factsFor(repo: string): ToolFacts {
  const manifest = json(resolve(repo, 'package.json'))
  const contributes = (manifest.contributes ?? {}) as {
    commands?: { command: string; title?: string }[]
  }
  const mcp = json(resolve(repo, 'mcp/package.json'))

  // Manifest titles are NLS placeholders (`%manifest.command.x.title%`); the
  // English strings live in package.nls.json. Rendering the placeholder would
  // put `%manifest.command.extract.title%` on the page.
  const nls = json(resolve(repo, 'package.nls.json')) as Record<string, string>
  const commands: ToolCommand[] = (contributes.commands ?? []).map(command => {
    const raw = command.title ?? ''
    const key = raw.startsWith('%') && raw.endsWith('%') ? raw.slice(1, -1) : ''
    return { id: command.command, title: key === '' ? raw : (nls[key] ?? raw) }
  })

  // `bundle.l10n.json` is the English source, not a translation.
  const locales = readdirSync(resolve(repo, 'l10n')).filter(file =>
    /^bundle\.l10n\.[a-z-]+\.json$/.test(file),
  ).length

  const zed = readFileSync(resolve(repo, 'zed/extension.toml'), 'utf8')
  const zedId = zed.match(/^id\s*=\s*"([^"]+)"/m)?.[1]
  if (zedId === undefined) throw new Error(`${repo}: zed/extension.toml has no id`)

  // Only scrape-le ships one today; the shape allows for more without a
  // second table to keep in step.
  const cargo = resolve(repo, 'crate/Cargo.toml')
  const crate = existsSync(cargo)
    ? (() => {
        const toml = readFileSync(cargo, 'utf8')
        const name = toml.match(/^name\s*=\s*"([^"]+)"/m)?.[1]
        const version = toml.match(/^version\s*=\s*"([^"]+)"/m)?.[1]
        if (name === undefined || version === undefined) {
          throw new Error(`${repo}: crate/Cargo.toml has no name or version`)
        }
        return { name, version }
      })()
    : undefined

  return {
    version: String(manifest.version),
    commands,
    locales,
    mcpPackage: String(mcp.name),
    zedId,
    ...(crate === undefined ? {} : { crate }),
  }
}

export function render(facts: ReadonlyMap<string, ToolFacts>): string {
  const entries = [...facts]
    .map(([id, fact]) => {
      const fields = [
        `version: '${fact.version}'`,
        `commands: ${JSON.stringify(fact.commands)}`,
        `locales: ${fact.locales}`,
        `mcpPackage: '${fact.mcpPackage}'`,
        `zedId: '${fact.zedId}'`,
        ...(fact.crate === undefined
          ? []
          : [`crate: { name: '${fact.crate.name}', version: '${fact.crate.version}' }`]),
      ].join(', ')
      return `  '${id}': { ${fields} },`
    })
    .join('\n')

  return `// Generated by scripts/sync-registry.ts — do not edit.
//
// Read from each extension repo: the manifest version and command count, the
// translated locale bundles, the MCP package name, and the Zed extension id.
// \`bun run sync:registry --check\` fails when this drifts from the repos.
import type { ToolFacts } from '../scripts/sync-registry'

export const TOOL_FACTS: Readonly<Record<string, ToolFacts>> = Object.freeze({
${entries}
})
`
}

export function main(
  check = process.argv.includes('--check'),
  fleet: string = FLEET,
  output: string = OUTPUT,
): number {
  const missing = TOOLS.filter(tool => !existsSync(resolve(fleet, tool.id, 'package.json')))
  if (missing.length > 0) {
    const names = missing.map(tool => tool.id).join(', ')
    if (check) {
      // CI and a Vercel build have no sibling checkouts. Refusing here would
      // fail every build for a condition that is normal off a dev machine.
      process.stdout.write(`sync-registry: skipped — no checkouts for ${names}.\n`)
      return 0
    }
    process.stderr.write(`\nsync-registry: no checkout for ${names} beside this repo.\n\n`)
    return 2
  }

  const facts = new Map(TOOLS.map(tool => [tool.id, factsFor(resolve(fleet, tool.id))]))
  const rendered = render(facts)

  if (check) {
    const committed = existsSync(output) ? readFileSync(output, 'utf8') : ''
    if (committed === rendered) {
      process.stdout.write(`Registry facts match the repos across ${facts.size} tools.\n`)
      return 0
    }
    process.stderr.write(
      '\nsync-registry: lib/tool-facts.generated.ts is out of date.\n' +
        'Run `bun run sync:registry` and commit the result.\n\n',
    )
    return 1
  }

  writeFileSync(output, rendered)
  for (const [id, fact] of facts) {
    process.stdout.write(
      `  ${id.padEnd(12)} v${fact.version}  ${String(fact.commands.length).padStart(2)} commands  ` +
        `${fact.locales} locales\n`,
    )
  }
  return 0
}

/* v8 ignore start -- process entry point; unreachable when imported by a test */
if (import.meta.main) {
  try {
    process.exit(main())
  } catch (cause) {
    const detail = cause instanceof Error ? (cause.stack ?? cause.message) : String(cause)
    process.stderr.write(`\nsync-registry: unexpected failure.\n${detail}\n\n`)
    process.exit(2)
  }
}
/* v8 ignore stop */
